### PR TITLE
jsonify our 500 errors.

### PR DESCRIPTION
**Pull request by haz**

### CODE REVIEW

**Comment by jan-dolejsi** [comment]
Hard to say. Sure this will let the 500 prevail? Well, let's try it!

**Comment by haz** [comment]
It'll still have errors, but at least the return will be json :P. I think that's the right interpretation -- if the flask server crashes down, that should be 500. But if the planner is on the fritz, then I think a json payload makes sense.

Going to merge -- @nirlipo , can you re-deploy?

**Comment by nirlipo** [comment]
Deployed! I tested Delfi to see if I get the same error that @jan-dolejsi was reporting, but it works fine now. Just in case I recompiled the images of each worker too.

**Comment by haz** [comment]
Any server-side indication of what's going on?

**Comment by nirlipo** [comment]
I'll send you a link with the failed task in the server monitor. The flags for persist were off, so I can't get more info than that it timed out. Looking at previous tasks that had the persist flag on, and delfi failed, it was related to tensorflow.

"stderr": "bash: cannot set terminal process group (1): Inappropriate ioctl for device\nbash: no job control in this shell\nUsing TensorFlow backend.\nError: Could not parse domain file: domain\nReason: Missing ')'.\nError: Could not parse domain file: domain\nReason: Missing ')'.\n",

**Pull request merged**
