### PR TITLE
Updating to modern packages.

### LINKED ISSUE #59: Python pip incompatibility
Sorry to keep up with these build issues, but there's an incompatibility between loading `celery==4.6.6` in `requirements.txt` and taking the latest version of `pip` (from `pip install --upgrade pip...`), as follows:

```
Collecting celery==4.4.6 (from -r requirements.txt (line 3))
  Downloading celery-4.4.6-py2.py3-none-any.whl.metadata (20 kB)
WARNING: Ignoring version 4.4.6 of celery since it has invalid metadata:
Requested celery==4.4.6 from https://files.pythonhosted.org/packages/f4/ba/ecec61c136cebd42430e51926296e1e8f740c7b7f5e2cbaae7b34c5f1295/celery-4.4.6-py2.py3-none-any.whl (from -r requirements.txt (line 3)) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
         ~^
Please use pip<24.1 if you need to use this version.
ERROR: Ignored the following yanked versions: 5.0.6, 5.2.5
ERROR: Could not find a version that satisfies the requirement celery==4.4.6 (from versions: 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.2.0, 0.3.0, 0.3.7, 0.3.20, 0.4.0, 0.4.1, 0.6.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.5, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.0.19, 3.0.20, 3.0.21, 3.0.22, 3.0.23, 3.0.24, 3.0.25, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19, 3.1.20, 3.1.21, 3.1.22, 3.1.23, 3.1.24, 3.1.25, 3.1.26.post1, 3.1.26.post2, 4.0.0rc3, 4.0.0rc4, 4.0.0rc5, 4.0.0rc6, 4.0.0rc7, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0rc1, 4.2.0rc2, 4.2.0rc3, 4.2.0rc4, 4.2.0, 4.2.1, 4.2.2, 4.3.0rc1, 4.3.0rc2, 4.3.0rc3, 4.3.0, 4.3.1, 4.4.0rc1, 4.4.0rc2, 4.4.0rc3, 4.4.0rc4, 4.4.0rc5, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.6, 4.4.7, 5.0.0a1, 5.0.0a2, 5.0.0b1, 5.0.0rc1, 5.0.0rc2, 5.0.0rc3, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.1.0b1, 5.1.0b2, 5.1.0rc1, 5.1.0, 5.1.1, 5.1.2, 5.2.0b1, 5.2.0b2, 5.2.0b3, 5.2.0rc1, 5.2.0rc2, 5.2.0, 5.2.1, 5.2.2, 5.2.3, 5.2.4, 5.2.6, 5.2.7, 5.3.0a1, 5.3.0b1, 5.3.0b2, 5.3.0rc1, 5.3.0rc2, 5.3.0, 5.3.1, 5.3.4, 5.3.5, 5.3.6, 5.4.0rc1, 5.4.0rc2, 5.4.0, 5.5.0b1)
ERROR: No matching distribution found for celery==4.4.6
```
Not sure if the right solution is to change the `celery` version, or ensure that we have a less-demanding `pip` version...

### PR DESCRIPTION
**Pull request by haz**
Fixes #59

### CODE REVIEW

**Comment by haz** [comment]
Can you have a quick look, @nirlipo , when you get a chance?

**Review by nirlipo — APPROVED** [review]

**Comment by nirlipo** [comment]
Flower seems to break with celery 5.x

See this thread: https://github.com/mher/flower/issues/1029

I'd revert to celery 4.x unless there's a workaround.

**Comment by haz** [comment]
@nirlipo On all the requirements.txt files? When I was going through and updating, it felt odd that we had so many copies of so similar lists. Any chance we could just unify to a single one at the top level, and COPY that into each of the images?

**Comment by nirlipo** [comment]
Yes, that makes sense, especially because they are almost the same.

**Comment by haz** [comment]
Working on this with #62

**Pull request merged**
